2025-04-18 13:30:25,318 INFO    Thread-6 (_run_job):60662 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-04-18 13:30:25,319 INFO    Thread-6 (_run_job):60662 [wandb_setup.py:_flush():67] Configure stats pid to 60662
2025-04-18 13:30:25,319 INFO    Thread-6 (_run_job):60662 [wandb_setup.py:_flush():67] Loading settings from /Users/rudra_sarkar/.config/wandb/settings
2025-04-18 13:30:25,319 INFO    Thread-6 (_run_job):60662 [wandb_setup.py:_flush():67] Loading settings from /Users/rudra_sarkar/Documents/PhD IIT Madras/Intro to Deep Learning M Khapra DA6401/da6401 assignment 2/wandb/settings
2025-04-18 13:30:25,319 INFO    Thread-6 (_run_job):60662 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-18 13:30:25,319 INFO    Thread-6 (_run_job):60662 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/rudra_sarkar/Documents/PhD IIT Madras/Intro to Deep Learning M Khapra DA6401/da6401 assignment 2/wandb/run-20250418_133025-sjowtrre/logs/debug.log
2025-04-18 13:30:25,319 INFO    Thread-6 (_run_job):60662 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/rudra_sarkar/Documents/PhD IIT Madras/Intro to Deep Learning M Khapra DA6401/da6401 assignment 2/wandb/run-20250418_133025-sjowtrre/logs/debug-internal.log
2025-04-18 13:30:25,319 INFO    Thread-6 (_run_job):60662 [wandb_init.py:init():761] calling init triggers
2025-04-18 13:30:25,320 INFO    Thread-6 (_run_job):60662 [wandb_init.py:init():766] wandb.init called with sweep_config: {'augment': True, 'batch_norm': False, 'batch_size': 64, 'conv_activation': 'gelu', 'dense': [32], 'dense_activation': 'sigmoid', 'dropout': 0.5, 'filter_initial': 64, 'filter_strategy': 'doubled', 'kernel': [5, 5, 3, 3, 3], 'learning_rate': 0.0008825649834390397, 'momentum': 0.8536762232747902, 'optimizer': 'sgd', 'resize': 64, 'weight_decay': 0.0030694873598227923}
config: {'batch_size': 64, 'resize': 64, 'filter_automated': True, 'filter_strategy': 'doubled', 'filter_initial': 64, 'n_convolutions': 5, 'filter_manual': [16, 32, 64, 128, 256], 'padding': True, 'stride': [1, 1, 1, 1, 1], 'dense': [512], 'kernel': [5, 5, 3, 3, 3], 'conv_activation': 'gelu', 'dense_activation': 'leaky_relu', 'n_dense': 1, 'optimizer': 'adam', 'augment': True, 'batch_norm': True, 'learning_rate': 0.0005437861534316687, 'momentum': 0.923087388297848, 'weight_decay': 0.008935689859547959, 'dropout': 0.1, 'xavier_init': False, 'wandb': False, 'wandb_entity': 'da24d008-iit-madras', 'wandb_project': 'da6401-assignment2', 'wandb_sweep': True, 'sweep_id': None, '_wandb': {}}
2025-04-18 13:30:25,320 INFO    Thread-6 (_run_job):60662 [wandb_init.py:init():784] starting backend
2025-04-18 13:30:25,320 INFO    Thread-6 (_run_job):60662 [wandb_init.py:init():788] sending inform_init request
2025-04-18 13:30:25,324 INFO    Thread-6 (_run_job):60662 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-04-18 13:30:25,325 INFO    Thread-6 (_run_job):60662 [wandb_init.py:init():803] backend started and connected
2025-04-18 13:30:25,327 INFO    Thread-6 (_run_job):60662 [wandb_run.py:_config_callback():1261] config_cb None None {'augment': True, 'batch_norm': False, 'batch_size': 64, 'conv_activation': 'gelu', 'dense': [32], 'dense_activation': 'sigmoid', 'dropout': 0.5, 'filter_initial': 64, 'filter_strategy': 'doubled', 'kernel': [5, 5, 3, 3, 3], 'learning_rate': 0.0008825649834390397, 'momentum': 0.8536762232747902, 'optimizer': 'sgd', 'resize': 64, 'weight_decay': 0.0030694873598227923}
2025-04-18 13:30:25,335 INFO    Thread-6 (_run_job):60662 [wandb_init.py:init():896] updated telemetry
2025-04-18 13:30:25,377 INFO    Thread-6 (_run_job):60662 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-04-18 13:30:25,844 INFO    Thread-6 (_run_job):60662 [wandb_init.py:init():995] starting run threads in backend
2025-04-18 13:30:26,029 INFO    Thread-6 (_run_job):60662 [wandb_run.py:_console_start():2377] atexit reg
2025-04-18 13:30:26,029 INFO    Thread-6 (_run_job):60662 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-18 13:30:26,029 INFO    Thread-6 (_run_job):60662 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-18 13:30:26,029 INFO    Thread-6 (_run_job):60662 [wandb_run.py:_redirect():2317] Redirects installed.
2025-04-18 13:30:26,029 INFO    Thread-6 (_run_job):60662 [wandb_init.py:init():1037] run started, returning control to user process
2025-04-18 13:31:01,331 INFO    MainThread:60662 [wandb_run.py:_finish():2112] finishing run da24d008-iit-madras/da6401-assignment2/sjowtrre
2025-04-18 13:31:01,335 INFO    MainThread:60662 [wandb_run.py:_atexit_cleanup():2342] got exitcode: 0
2025-04-18 13:31:01,336 INFO    MainThread:60662 [wandb_run.py:_restore():2324] restore
2025-04-18 13:31:01,336 INFO    MainThread:60662 [wandb_run.py:_restore():2330] restore done
2025-04-18 13:31:01,766 WARNING MsgRouterThr:60662 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-04-18 13:31:01,767 INFO    MsgRouterThr:60662 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
